# CRUD user
api_user_list:
    path: /api/users
    controller: App\Controller\UserController::list
    methods: [GET]

api_user_read:
    path: /api/users/{id}
    controller: App\Controller\UserController::read
    methods: [GET]

api_user_update:
    path: /api/users/{id}
    controller: App\Controller\UserController::update
    methods: [PUT]

api_user_create:
    path: /api/users
    controller: App\Controller\UserController::create
    methods: [POST]

api_user_delete:
    path: /api/users/{id}
    controller: App\Controller\UserController::delete
    methods: [DELETE]

api_user_delete_all:
    path: /api/users
    controller: App\Controller\UserController::deleteAll
    methods: [DELETE]

login:
    path: /api/login
    controller: App\Controller\SecurityController::login
    methods: [POST]

#user_profile_read:
#    path: /profile
#    controller: App\Controller\UserController::deleteAll
#    methods: [GET]
